Repository HON95/prometheus-nut-exporter, pull requests merged in 2022-01, with the labels that each got.

#19 Metric add: ups.temperature
  README.md
  src/metrics.rs
Labels: enhancement, metric

#22 Fix a typo in print_ups_info_metric
  src/openmetrics_builder.rs
Labels: bug

#21 Implement IP binding by adding the HTTP_IP variable
  README.md
  src/config.rs
  src/http_server.rs
Labels: enhancement
